language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
addons:
  code_climate:
    repo_token: 6fecc8e90fddce9a0722e5ead3993b15f96905caa4775f392a8eca5fe57e6eca
after_script:
  - cat coverage/lcov.info | codeclimate